#!/bin/bash
#################
# Be sure these directories exist: in your $HOME_DiR:
# pdfs - put your pdfs here
# full_text - this is where the script will write the extracted FULL_TEXT files
#################
HOME_DIR="/home2/lisham/diglib-15/dhiSpace/apw/2018-06-13-batch-7"
SOURCE_DIR="$HOME_DIR/pdfs"
OUTPUT_DIR="$HOME_DIR/full_text"

echo "HOME_DIR=$HOME_DIR"
echo "SOURCE_DIR=$SOURCE_DIR"
echo "OUTPUT_DIR=$OUTPUT_DIR"

cd "$SOURCE_DIR"

for f in *;
	do
	echo "f = $f"
	# GET THE CORE NAME OF THE CURRENT FILE -- MINUS THE EXTENSION
	FILENAME="${f%%.*}"

	echo "FILENAME = $FILENAME"

	# CREATE FULL_TEXT.txt - extract text from the PDF
	# You can safely ignore error messages regarding fonts generated by pdftotext.

	# echo "Extracting text from $PDF ..."
	pdftotext -enc UTF-8 "$f" "$OUTPUT_DIR/$FILENAME.txt"

	#       echo -e "creating JPEG\n"
	#       convert -resize 800 "$f" "$OUTPUT_DIR/$OBJECT/$DIRNAME/JPG.jpg"

	#       echo -e "creating OCR\n"
	#       /usr/local/bin/tesseract "$f" "$OUTPUT_DIR/$OBJECT/$DIRNAME/OCR" -l eng

	#       echo -e "creating HOCR\n"
	#       /usr/local/bin/tesseract "$f" "$OUTPUT_DIR/$OBJECT/$DIRNAME/HOCR" -l eng hocr

	#       echo -e "creating HOCR\n"
	#       /usr/local/bin/tesseract "$f" "$OUTPUT_DIR/$OBJECT/$DIRNAME/HOCR" -l eng hocr

done