https://github.com/islandora/islandora/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_badges/archive/7.x-1.10.zip
https://github.com/islandora/islandora_bagit/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_batch/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_book_batch/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_bookmark/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_checksum/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_checksum_checker/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_drupal_filter/releases/tag/7.1.10
https://github.com/Islandora/islandora_fits/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_form_fieldpanel/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_importer/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_internet_archive_bookreader/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_marcxml/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_newspaper_batch/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_oai/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_ocr/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_openseadragon/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_paged_content/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_pathauto/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_pdfjs/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_populator/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_premis/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_scholar/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_simple_workflow/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_solr_facet_pages/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_solr_metadata/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_solr_search/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_solr_views/archive/7.x-1.10.zip
https://github.com/islandora/islandora_solution_pack_audio/archive/7.x-1.10.zip
https://github.com/islandora/islandora_solution_pack_book/archive/7.x-1.10.zip
https://github.com/islandora/islandora_solution_pack_collection/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_solution_pack_compound/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_solution_pack_disk_image/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_solution_pack_entities/archive/7.x-1.10.zip
https://github.com/islandora/islandora_solution_pack_image/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_solution_pack_large_image/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_solution_pack_newspaper/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_solution_pack_pdf/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_solution_pack_video/archive/7.x-1.10.zip
https://github.com/islandora/islandora_solution_pack_web_archive/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_usage_stats/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_videojs/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_xacml_editor/archive/7.x-1.10.zip
https://github.com/Islandora/islandora_xml_forms/archive/7.x-1.10.zip
https://github.com/islandora/islandora_xmlsitemap/archive/7.x-1.10.zip
https://github.com/Islandora/objective_forms/archive/7.x-1.10.zip
https://github.com/Islandora/php_lib/archive/7.x-1.10.zip

https://github.com/islandora/tuque/archive/1.10.zip
