#!/bin/bash
##################
# Purpose: Used in the APWA project to extract text from clean print PDFs (handwritten PDFs must not be in this directory).
# Reads a directory of *.pdf files
# Extracts the embedded text.
# Writes a *.txt file to the same directory
# You can safely ignore error messages regarding fonts generated by pdftotext.
# Manual move the *.txt files to the "full_text" for the preingest to use when creating the ingest file structure and zip file.
##################
FILES=~/diglib-15/LibSpace/drop-box/Ready-for-Peter/from-Metalogers/APWA-14490/pdfs/*.pdf

for f in $FILES
do

	echo "Processing $f file..."

	pdftotext -eol unix -enc UTF-8 $f

done

# Available encodings
# UCS-2
# ASCII7
# Latin1
# UTF-8 (preferred)
# ZapfDingbats
# Symbol
