ren Bill-Dobbins.doc yhm-jaz-dobbins-bill.doc
ren Bob-Kinkel.doc yhm-jaz-kinkel-bob.doc
ren Bruce-Johnstone.doc yhm-jaz-johnstone-bruce.doc
ren Burrill-Crohn.doc yhm-jaz-crohn-burrill.doc
ren Carl-Allen.doc yhm-jaz-allen-carl.doc
ren Carmen-Caramanica.doc yhm-jaz-caramanica-carmen.doc
ren Carol-Bash.doc yhm-jaz-bash-carol.doc
ren Chazz-Frichtel.doc yhm-jaz-frichtel-chazz.doc
ren Chuck-Mancuso..doc yhm-jaz-mancuso-chuck.doc
ren Clay-Jenkins.doc yhm-jaz-jenkins-clay.doc
ren Dan-Morgenstern.doc yhm-jaz-morgenstern-dan.doc
ren Danny-D'Imperio.doc yhm-jaz-d'imperio-danny.doc
ren Dave-Rivello.doc yhm-jaz-rivello-dave.doc
ren David-Finck.doc yhm-jaz-finck-david.doc
ren Derrick-Gardner.doc yhm-jaz-gardner-derrick.doc
ren Eddie-Metz-Jr.doc yhm-jaz-metz-eddie.doc
ren Eric-Alexander.doc yhm-jaz-alexander-eric.doc
ren Evan-Christopher.doc yhm-jaz-christopher-evan.doc
ren Gap-Mangione.doc yhm-jaz-mangione-gap.doc
ren Gary-Smulyan.doc yhm-jaz-smulyan-gary.doc
ren Giacomo-Gates.doc yhm-jaz-gates-giacomo.doc
ren Greg-Thomas.doc yhm-jaz-thomas-greg.doc
ren Hakan-Rydin.doc yhm-jaz-rydin-hakan.doc
ren Harold-Mabern.doc yhm-jaz-mabern-harold.doc
ren Hide-Tanaka.doc yhm-jaz-tanaka-hide.doc
ren Howie-Shear.doc yhm-jaz-shear-howie.doc
ren Ingrid-Sertso.doc yhm-jaz-sertso-ingrid.doc
ren Iola-Brubeck.doc yhm-jaz-brubeck-iola.doc
ren Jane-Monheit.doc yhm-jaz-monheit-jane.doc
ren Janis-Siegel.doc yhm-jaz-siegel-janis.doc
ren Javon-Jackson.doc yhm-jaz-jackson-javon.doc
ren Jay-Leonhart-Part-II.doc yhm-jaz-leonhart-jay-ii.doc
ren Jim-Cullum..doc yhm-jaz-cullum-jim.doc
ren Jimmy-Heath.doc yhm-jaz-heath-jimmy.doc
ren Joe-Magnarelli.doc yhm-jaz-magnarelli-joe.doc
ren Joey-Morant.doc yhm-jaz-morant-joey.doc
ren John-Fedchock.doc yhm-jaz-fedchock-john.doc
ren Jon-Jang-Part-II.doc yhm-jaz-jang-jon-ii.doc
ren Jon-Weber.doc yhm-jaz-weber-jon.doc
ren Karl-Berger.doc yhm-jaz-berger-karl.doc
ren Laurence-Juber.doc yhm-jaz-juber-laurence.doc
ren Marty-Morell.doc yhm-jaz-morell-marty.doc
ren Michi-Fuji.doc yhm-jaz-fuji-michi.doc
ren Mitchell-Player.doc yhm-jaz-player-mitchell.doc
ren Nicki-Parrott.doc yhm-jaz-parrott-nicki.doc
ren Peter-Appleyard.doc yhm-jaz-appleyard-peter.doc
ren Ralph-LaLama.doc yhm-jaz-lalama-ralph.doc
ren Ray-Brown.doc yhm-jaz-brown-ray.doc
ren Rick-Montalbano.doc yhm-jaz-montalbano-rick.doc
ren Robert-Glasper.doc yhm-jaz-glasper-robert.doc
ren Rossano-Sportiello.doc yhm-jaz-sportiello-rossano.doc
ren Rufus-Reid.doc yhm-jaz-reid-rufus.doc
ren Ruth-and-Bucky-Pizzarelli.doc yhm-jaz-pizzarelli-ruth-and-bucky.doc
ren Ruth-Brisbane.doc yhm-jaz-brisbane-ruth.doc
ren Sam-Kininger.doc yhm-jaz-kininger-sam.doc
ren Vincent-Pelote.doc yhm-jaz-pelote-vincent.doc
ren Warren-Bernhardt.doc yhm-jaz-bernhardt-warren.doc
ren Winard-Harper.doc yhm-jaz-harper-winard.doc
